### ISSUE TITLE
Kafka 1.0

### ISSUE THREAD

**Issue by AssafKatz3** [taion809/kafka-cli#1]
Is it any plan to update it?
Thanks

**Comment by taion809** [comment]
Didn't know anyone was using this; i'll update when I get off work 👍

**Comment by AssafKatz3** [comment]
We still not using it, we will need it soon :-) It is good for [HELM hook](https://github.com/kubernetes/helm/blob/master/docs/charts_hooks.md)

**Comment by taion809** [comment]
upgraded to kafka 1.0.0, thanks again

https://hub.docker.com/r/taion809/kafka-cli/tags/
